### ISSUE TITLE
Preparing ios on Windows using the cordova CLI

### ISSUE THREAD

**Issue by TheCell** [Wikitude/wikitude-cordova-plugin#128]
Hey there
We use the Cordova Plugin with Phonegap for our projects.

I am using windows and I'm preparing the ios version aswell on windows, copy it to a mac machine and run it then. But after the 7.0 SDK I am unable to prepare the ios Version. Even if I clone the git locally and add the wikitude via local path the same problem persists.

I guess my Problem is that there is only an .sh script provided to combine the ios files inside WikitudeSDK.framework. Here is the error message

```
Running command: cmd "/s /c "sh C:\Users\Administrator\Documents\cordova\wikionly\plugins\com.wikitude.phonegap.WikitudePlugin\scripts\configure_wikitude_sdk_framework.sh C:\Users\Administrator\Documents\cordova\wikionly""
Der Befehl "sh" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Failed to install 'com.wikitude.phonegap.WikitudePlugin': Error: Hook failed with error code 1: C:\Users\Administrator\Documents\cordova\wikionly\plugins\com.wikitude.phonegap.WikitudePlugin\scripts\configure_wikitude_sdk_framework.sh
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:232:23
    at _rejected (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:864:24)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:808:41)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:624:44
    at runSingle (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:137:13)
    at flush (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Hook failed with error code 1: C:\Users\Administrator\Documents\cordova\wikionly\plugins\com.wikitude.phonegap.WikitudePlugin\scripts\configure_wikitude_sdk_framework.sh
```

When I create a new app on ios and add wikitude it compiles everything and combines the Files inside WikitudeSDK.framework.
At the moment (on windows:) I change the app to my desire, prepare the ios, copy the content of the platforms/ios over to the Mac.
Then on the Mac I have a temporary Cordova project with the Wikitude Plugin.
I then have to manually copy the WikitudeSDK.framework from the new temporary project to my original project and change the Xcode Project infos. Changing the Xcode Project means: add "WikitudeSDK.framework" to "Embedded Binaries" and remove it from "Linked Frameworks and Libraries"

Any plans to add a script to combine and prepare the ios version plugin on Windows?

Greetings
TheCell

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @TheCell,
Do you know if the command line tool `lipo` is available on Windows? Our script highly depends on this tool.

Best regards,
Andreas

**Comment by TheCell** [comment]
Hey @AndreasSchacherbauerWikitude I haven't used `lipo` but a quick google rampage did not reveal anything windows related. I guess it is not available on windows. Any plans to dig into this problem any further?

Best regards, thanks
TheCell
